### PR TITLE
Add German Translation

### PR DESCRIPTION
**Pull request by sebastian-marinescu**
This adds a German translation and also fixes the English failure_desc value.

### CODE REVIEW

**Comment by BobRay** [comment]
Thanks!

**Comment by sebastian-marinescu** [comment]
Hi Bob,

sure, no problem. I'm seeing the new strings and I'll translate them on the
weekend, if that's sufficient for you :)
And I'd do it through a PR as I'm okay with Github.

With best regards,
Sebastian
-- 
*Sebastian G. Marinescu*
// Consulting & Development

T +49 (0) 69 20 165 681 <javascript:void(0);>
F +49 (0) 69 20 165 682
M +49 (0) 178 83 48 389 <javascript:void(0);>

connect with me
via Xing <https://www.xing.com/profile/SebastianG_Marinescu> or LinkedIn
<https://www.linkedin.com/pub/sebastian-g-marinescu/b7/5b5/291>

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte
Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail
irrtümlich erhalten haben, informieren Sie bitte sofort den Absender
und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte
Weitergabe dieser E-Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient or have received this e-mail in error please
notify the sender immediately and destroy this e-mail. Any unauthorized
copying, disclosure or distribution of the material in this e-mail is
strictly forbidden.

**Comment by BobRay** [comment]
Thanks Sebastian,

That would be great.

**Comment by sebastian-marinescu** [comment]
Hi Bob,

it's done, you can merge ;)

With best regards,
Sebastian

-- 
*Sebastian G. Marinescu*
// Consulting & Development

T +49 (0) 69 20 165 681 <javascript:void(0);>
F +49 (0) 69 20 165 682
M +49 (0) 178 83 48 389 <javascript:void(0);>

connect with me
via Xing <https://www.xing.com/profile/SebastianG_Marinescu> or LinkedIn
<https://www.linkedin.com/pub/sebastian-g-marinescu/b7/5b5/291>

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte
Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail
irrtümlich erhalten haben, informieren Sie bitte sofort den Absender
und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte
Weitergabe dieser E-Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you
are not the intended recipient or have received this e-mail in error please
notify the sender immediately and destroy this e-mail. Any unauthorized
copying, disclosure or distribution of the material in this e-mail is
strictly forbidden.

**Comment by BobRay** [comment]
Thanks!

BTW, This one is wrong:

+ $_lang['ugm_modified_for_upgrade_by'] = 'Modified for UpgradeModx only
with dashboard widget by';

It really should read 'Modified for upgrade only ... '

The original script did both upgrade and clean installs.

Cheers,

Bob

**Comment by sebastian-marinescu** [comment]
Hi Bob, okay, sorry for over-correcting :)
Next time I'll know now ;)

**Comment by BobRay** [comment]
Can you email me the German translation for that line?  I'll just plug it
in.

**Comment by sebastian-marinescu** [comment]
Hi @BobRay, we are still discussing in the wrong PR :) 
I'm not talking about the credit/signature inside the code-files, that's okay. 
I'm talking about the messages through email that got public here on GitHub, with my signature and all.
I'll check the translation in https://github.com/BobRay/UpgradeMODX now 👍

**Comment by BobRay** [comment]
LOL, sorry -- asleep at the switch.  I will delete the comments, but you should change your GitHub profile (if you haven't already) so your email won't be shown.

**Pull request merged**
